### ISSUE TITLE
unable to access yaml keys starting with dot

### ISSUE THREAD

**Issue by zerog2k** [openuado/niet#79]
I'm not able to access yaml keys starting with dot, e.g. `.foo:`
Not sure if I'm doing it wrong, or if this is some issue with jmespath implementation under the hood.

```
bash-3.2$ pip3 freeze | grep niet
niet==3.2.0
bash-3.2$ cat test.yml
.foo:
  something: "here"

bar:
  something: "there"
bash-3.2$ python3 -m niet bar test.yml
something: there

bash-3.2$ python3 -m niet foo test.yml
Element not found: foo
bash-3.2$ python3 -m niet .foo test.yml
Element not found: foo
bash-3.2$ python3 -m niet \.foo test.yml
Element not found: foo
bash-3.2$ python3 -m niet .\.foo test.yml
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/niet/__main__.py", line 5, in <module>
    main()
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/niet/__init__.py", line 282, in main
    result = get(data, search, silent)
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/niet/__init__.py", line 206, in get
    cursor = search(keywords, data)
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/jmespath/__init__.py", line 12, in search
    return parser.Parser().parse(expression).search(data, options=options)
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/jmespath/parser.py", line 88, in parse
    parsed_result = self._do_parse(expression)
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/jmespath/parser.py", line 96, in _do_parse
    return self._parse(expression)
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/jmespath/parser.py", line 111, in _parse
    parsed = self._expression(binding_power=0)
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/jmespath/parser.py", line 124, in _expression
    left = nud_function(left_token)
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/jmespath/parser.py", line 440, in _error_nud_token
    self._raise_parse_error_for_token(token, 'invalid token')
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/jmespath/parser.py", line 476, in _raise_parse_error_for_token
    raise exceptions.ParseError(lex_position, actual_value,
jmespath.exceptions.ParseError: invalid token: Parse error at column 0, token "." (DOT), for expression:
".foo"
 ^
bash-3.2$ python3 -m niet '.foo' test.yml
Element not found: foo
bash-3.2$ python3 -m niet .'.foo' test.yml
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/niet/__main__.py", line 5, in <module>
    main()
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/niet/__init__.py", line 282, in main
    result = get(data, search, silent)
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/niet/__init__.py", line 206, in get
    cursor = search(keywords, data)
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/jmespath/__init__.py", line 12, in search
    return parser.Parser().parse(expression).search(data, options=options)
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/jmespath/parser.py", line 88, in parse
    parsed_result = self._do_parse(expression)
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/jmespath/parser.py", line 96, in _do_parse
    return self._parse(expression)
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/jmespath/parser.py", line 111, in _parse
    parsed = self._expression(binding_power=0)
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/jmespath/parser.py", line 124, in _expression
    left = nud_function(left_token)
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/jmespath/parser.py", line 440, in _error_nud_token
    self._raise_parse_error_for_token(token, 'invalid token')
  File "/Users/jjensen/Library/Python/3.9/lib/python/site-packages/jmespath/parser.py", line 476, in _raise_parse_error_for_token
    raise exceptions.ParseError(lex_position, actual_value,
jmespath.exceptions.ParseError: invalid token: Parse error at column 0, token "." (DOT), for expression:
".foo"
 ^
bash-3.2$ 
```

**Comment by zerog2k** [comment]
looks like a workaround is to double-wrap in quotes:
```
bash-3.2$ python3 -m niet  '".foo"' test.yml
something: here

```
probably a limitation in jmespath ?

**Comment by 4383** [comment]
Yeah I think this is a side effect of jmespath.

**Comment by 4383** [comment]
So, I confirm that this is a side effect of the way jmespath behave.

I added some examples to the doc to highlight this topic https://github.com/openuado/niet/commit/1642a3c1e2fa9eb68cf370f82a2833286023f571

I think we can close this issue. 

Thanks @zerog2k
