### ISSUE TITLE
Errors parsing lists of dictionaries

### ISSUE THREAD

**Issue by sg3-141-592** [openuado/niet#81]
Tested using `niet ==3.2.0` and `python 3.11.1`

When trying to parse dictionaries that are in a list we get an error

``` yaml
hello:
  world:
    - abc : 123
    - def : 456
```

```
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/3.11.1/bin/niet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/niet/__init__.py", line 287, in main
    print_result(result, out_format, in_format, search, out_file)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/niet/__init__.py", line 226, in print_result
    output = VALID_PRINTERS[out_format]["cmd"](res, search)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/niet/output.py", line 80, in print_eval
    results = _findevalitem(res, search)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/niet/output.py", line 64, in _findevalitem
    item = _findevalitem(v, k)
           ^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/niet/output.py", line 69, in _findevalitem
    el.append("{k}=( {value} )".format(k=k, value=" ".join(v)))
                                                  ^^^^^^^^^^^
```

**Comment by 4383** [comment]
Hello,

Thanks for reporting this issue and sorry for the late reply.

I think the error is related to the presence of the dash in lines with `abc` and `def`.

If I remove these dashes, then, the error disappear:

```
tox -r -e venv -- niet -f eval . /tmp/test.yaml
venv: remove tox env folder /home/dev/niet/.tox/venv
.pkg: remove tox env folder /home/dev/niet/.tox/.pkg
venv: install_deps> pip install -r /home/dev/niet/test-requirements.txt
.pkg: install_requires> python -I -m pip install 'hatch-vcs>=0.3' 'hatchling>=1.12.2'
.pkg: _optional_hooks> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build
.pkg: get_requires_for_build_editable> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build
.pkg: build_editable> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build
venv: install_package_deps> pip install 'jmespath>=0.9.4' pytoml 'pyyaml>=5.1'
venv: install_package> pip install --force-reinstall --no-deps /home/dev/niet/.tox/.tmp/package/19/niet-3.2.1.dev2+g1642a3c-py3-none-any.whl
venv: commands[0]> niet -f eval . /tmp/test.yaml
hello__world__abc="123";hello__world__def="456"
.pkg: _exit> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True hatchling.build
  venv: OK (8.86=setup[8.76]+cmd[0.10] seconds)
  congratulations :) (8.99 seconds)
```

Is these dashes are mandatory?
